--- 
phases:

  pre_build: 
    commands: 
      - "echo Using AWS Account: $AWS_ACCESS_KEY_ID"
      - "aws sts get-caller-identity"
      - export CODEBUILD_GIT_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
      - if [ "$CODEBUILD_GIT_BRANCH" = "" ] ; then
          CODEBUILD_GIT_BRANCH="$(git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }')";
          export CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH#remotes/origin/};
        fi
      - export DEPLOY_ENVIRONMENT="${CODEBUILD_GIT_BRANCH:4}"
      - "echo Linting Project..."
      - "echo Environment variables:"
      - "printenv"
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Running plan on VPC terraform deployment stack..."
      - "runway plan --tag vpc --ci"
      - "echo running plan on K8 Cluster terraform deployment stack"
      - "runway plan --tag kube --ci"
      - "echo Running plan on imgmgr k8 deployment stack"
      - "runway plan --tag imgmgr --ci"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
version: 0.2
