apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
  labels:
    app: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacman
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
      - name: pacman
        image: brandonspell08/pacmancanvas:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
          name: pacport
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "200Mi"
            cpu: "200m"
