apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgmgr
  labels:
    app: imgmgr-capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: imgmgr-capstone
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: imgmgr-capstone
    spec:
      containers:
      - name: flask-imgmgr
        image: brandonspell08/flask-imgmgr:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "200Mi"
            cpu: "200m"
        env:
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: imgmgr-map
              key: bucketName
        - name: PACMAN_URL
          valueFrom:
            configMapKeyRef:
              name: imgmgr-map
              key: pacman.url
